- name: check for {{ name }} subvolume
  command: btrfs subvolume show {{ path }}
  register: data_subvolume_result
  ignore_errors: True
  with_items: "{{ ansible_mounts }}"
  when:
    - item.mount == '/'
    - item.fstype == 'btrfs'

- name: create {{ name }} subvolume
  command: btrfs subvolume create {{ path }}
  when: data_subvolume_result | failed

- file: path={{ path }} state=directory \
        owner={{ owner | default('root') }} group={{ group | default('root') }} \
        mode={{ mode | default('0700') }}

