- name: create data volume parent directory
  file: path={{ container_data_directory | dirname }} state=directory owner=root group=root \
        mode=0755

- name: check for container data subvolume
  command: btrfs subvolume show {{ container_data_directory }}
  register: data_subvolume_result
  ignore_errors: True
  with_items: "{{ ansible_mounts }}"
  when:
    - item.mount == '/'
    - item.fstype == 'btrfs'

- name: create container data subvolume
  command: btrfs subvolume create {{ container_data_directory }}
  when: data_subvolume_result | failed
