- include_vars: owncloud.yml
- include_vars: secret_vars/owncloud.yml

- name: Owncloud Postgres image
  docker_image:
    name: docker.io/postgres
    tag: "{{ owncloud_pg_version }}"

- name: Owncloud database container
  docker_container:
    name:  owncloud-db
    image: "postgres:{{ owncloud_pg_version }}"
    state: started
    env:
      POSTGRES_USER:     "{{ owncloud_pg_username }}"
      POSTGRES_PASSWORD: "{{ owncloud_pg_password }}"

- name: Owncloud application image
  docker_image:
    name: docker.io/owncloud
    tag: "{{ owncloud_version }}"

- name: Owncloud application container
  docker_container:
    name:  owncloud-app
    image: "owncloud:{{ owncloud_version }}"
    state: started
    published_ports: 80:80
    links:
      - owncloud-db:db

- name: Owncloud SSL proxy image
  docker_image:
    name: danieldent/nginx-ssl-proxy
    # "latest" is the only available tag
    tag:  latest
