- name: "deploy docker hosts"
  hosts: docker
  become: true
  become_user: root
  roles:
    - { role: common, tags: ['common'] }
    - { role: docker, tags: ['docker'] }

- include: container-base.yml
  vars:
    container_play_action: deploy
    state: started
