- name: configure ansible base (local)
  hosts: container-servers
  run_once: True
  connection: local
  roles:
    - { role: base, tags: ['always'] }

- name: configure Docker (local)
  hosts: container-servers
  run_once: True
  connection: local
  roles:
    - { role: docker-common, tags: ['always'], docker_server: False }

- name: configure ansible base
  hosts: container-servers
  become: true
  roles:
    - { role: base, tags: ['always'] }

- name: "{{ container_play_action }} containers"
  hosts: container-servers
  become: true
  become_user: root
  roles:
    - { role: syncthing, tags: ['syncthing'] }
    - { role: dnsmasq,   tags: ['dnsmasq'] }
