- name: "configure arch base"
  hosts: docker&:arch
  become: true
  become_user: root
  roles:
    - { role: arch, tags: ['arch'] }

- name: "deploy docker hosts"
  hosts: docker
  become: true
  become_user: root
  roles:
    - { role: common, tags: ['common'] }
    - { role: docker, tags: ['docker'] }

- include: container-base.yml
  vars:
    container_play_action: deploy
    state: started
