- name: configure ansible base
  hosts: container-servers
  become: true
  roles:
    - { role: base, tags: ['always'] }

- name: "{{ container_play_action }} containers"
  hosts: container-servers
  become: true
  become_user: root
  roles:
    - { role: docker-registry, tags: ['docker-registry'] }
    - { role: mumble, tags: ['mumble'] }
    - { role: owncloud, tags: ['owncloud'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: le-gen, tags: ['le-gen'] }
    - { role: crashplan, tags: ['crashplan'] }
    - { role: terraria, tags: ['terraria'] }
    - { role: minecraft, tags: ['minecraft'] }
