- name: restart containers
  hosts: test
  vars:
    state: started
    restart: yes
  become: true
  become_user: root

  roles:
    - { role: mumble,   tags: ['mumble'] }
    - { role: owncloud, tags: ['owncloud'] }
    - { role: ssh,      tags: ['ssh'] }
