---

- include_role: name=docker-container private=True
  vars:
    container_name: minecraft-{{ mcserv.name | lower | replace(' ', '-') }}
    image_name: minecraft
    tag: "{{ mcserv.modpack_name | lower | replace(' ', '-') }}-{{ mcserv.modpack_version }}"
    git_repo: https://github.com/jkoelndorfer/dockerfiles.git
    build_subdirectory: "minecraft/forge-server"
    published_ports:
      - "{{ mcserv.port }}:25565"
    buildargs:
      MODPACK_SERVER_ZIP_URL: "{{ mcserv.server_zip_url }}"
    volumes:
      - src: backups
        dest: /minecraft/backups
        mount_mode: rw

      - src: serverconf
        dest: /minecraft/serverconf
        mount_mode: rw

      - src: world
        dest: /minecraft/world
        mount_mode: rw
  static: False
  with_items: "{{ minecraft_servers }}"
  loop_control:
    loop_var: mcserv
