---

- name: create container data volume -- {{ container_name }}
  include_role: name=volume private=True
  vars:
    path: "{{ container_data_directory }}/{{ container_name }}"
    owner: root
    group: root
    mode: 0755
    btrfs_subvolume: btrfs_volumes
  static: True

- name: create container data directories -- {{ container_name }}
  file:
    path: "{{ item.src if item.src[0] == '/' else '/'.join([container_data_directory, container_name, item.src]) }}"
    state: directory
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  become: True
  register: container_data_directories
  with_items: "{{ volumes }}"
  when: item.type is not defined or item.type == 'directory'

- name: set this container data directory
  set_fact:
    this_container_data_directory: "{{ container_data_directory }}/{{ container_name }}"

- name: run container-specific configuration tasks -- {{ container_name }}
  include: "{{ config_tasks }}"
  when: config_tasks is defined

- name: "container -- {{ container_name }}"
  docker_container:
    name:  "{{ container_name }}"
    image: "{{ (docker_registry + '/' + image_name) if git_repo is defined else image_name }}:{{ tag }}"
    state: "{{ state }}"
    command: "{{ command | default(omit) }}"
    restart: "{{ restart | default(omit) }}"
    restart_policy: "{{ restart_policy | default('always') }}"
    expose: "{{ expose | default(omit) }}"
    published_ports: "{{ published_ports | default(omit) }}"
    links: "{{ links | default(omit) }}"
    hostname: "{{ hostname | default(omit) }}"
    volumes: >-
      [
        {% for v in (volumes | default([])) %}
        "{{ (v.src if v.src[0] == '/' else '/'.join([container_data_directory, container_name, v.src])) +
           ":" + v.dest + ":" + (v.mount_mode | default('rw')) }}"{% if not loop.last %},{% endif %}
        {% endfor %}
      ]
    env: "{{ env | default(omit) }}"
    tty: true
    interactive: true
  become: True
