- include: roles/docker/tasks/image.yml
  vars:
    task_name: Terraria server container image
    name: ryshe/terraria
    tag: latest

- include: common_tasks/container-data.yml
  vars:
    container_name: terraria
    owner: root
    group: root
    mode: '0755'

- file: path={{ container_data_directory }}/terraria/main state=directory owner=root group=root mode=0755

- include: roles/docker/tasks/container.yml
  vars:
    task_name: Terraria server container {{ item.world_name }}
    name:  terraria-{{ item.world_name }}
    image: docker.io/ryshe/terraria:latest
    command: "-world /world/{{ item.world_name }}.wld -autocreate {{ {'small': 1, 'medium': 2, 'large': 3 }[item.world_size] }}"
    expose:
      - "7777"
    published_ports:
      - "{{ item.port }}:7777"
    volumes:
      - "{{ container_data_directory }}/terraria/main:/world:rw"
  with_items: "{{ terraria_worlds }}"
