- include_role: name=docker-container private=True
  vars:
    container_name: terraria-{{ tsrv.world_name }}
    image_name: docker.io/ryshe/terraria
    tag: latest
    command: >-
      -world /world/{{ tserv.world_name }}.wld
      -autocreate {{ {'small': 1, 'medium': 2, 'large': 3 }[tserv.world_size] }}
    expose:
      - "7777"
    published_ports:
      - "{{ tserv.port }}:7777"
    volumes:
      - src: world
        dest: /world
        mount_mode: rw
  with_items: "{{ terraria_worlds }}"
  loop_control:
    loop_var: tserv
  static: False
