- name: "{{ task_name }} ({{ state }})"
  docker_container:
    name:  "{{ name }}"
    image: "{{ docker_registry + '/' + registry_image if registry_image else image }}"
    state: "{{ state }}"
    command: "{{ command | default(None) }}"
    restart: "{{ restart | default(false) }}"
    restart_policy: "{{ restart_policy | default('always') }}"
    expose: "{{ expose | default([]) }}"
    published_ports: "{{ published_ports | default([]) }}"
    links: "{{ links | default([]) }}"
    hostname: "{{ hostname | default(None) }}"
    volumes: "{{ volumes | default([]) }}"
    env: "{{ env | default({}) }}"
    tty: true
    interactive: true
