- include_vars: "{{ ansible_os_family }}.yml"

- name: install Docker package
  package: name={{ docker_package }} state=installed
  notify: restart Docker
  become: True

- service: name={{ docker_service }} state=started enabled=true
  become: True
