- file: path={{ container_data_directory }}/ssh/home state=directory owner=root group=root mode=0755

- name: check for ssh data subvolume
  command: btrfs subvolume show {{ container_data_directory }}/ssh
  register: data_subvolume_result
  ignore_errors: True
  with_items: "{{ ansible_mounts }}"
  when:
    - item.mount == '/'
    - item.fstype == 'btrfs'

- name: create container ssh data subvolume
  command: btrfs subvolume create {{ container_data_directory }}/ssh
  when: data_subvolume_result | failed
