- include_vars: secret_vars/user-account.yml

- include: common_tasks/docker-image-from-git.yml
  vars:
    task_name: CentOS ssh image
    name: centos-shell
    tag: latest
    git_repo: https://github.com/jkoelndorfer/centos-shell

- include: data.yml

- include: common_tasks/docker-container.yml
  vars:
    task_name: CentOS ssh container
    name:  ssh
    image: centos-shell
    published_ports: "22:22"
    hostname: sh.segv.us
    volumes:
      - "{{ container_data_directory }}/ssh/home:/home:rw"
      - "{{ container_data_directory }}/ssh/host_keys:/etc/ssh/host_keys:rw"
    env:
      USER_NAME: "{{ primary_user_username }}"
      USER_SHELL: "{{ preferred_shell }}"
      USER_ID: "{{ primary_user_uid }}"
