- include_vars: secret_vars/user-account.yml

- include: common_tasks/docker-image-from-git.yml
  vars:
    task_name: Fedora ssh image
    name: fedora-shell
    tag: latest
    git_repo: https://github.com/jkoelndorfer/docker-shell
    git_version: fedora

- include: data.yml

- include: common_tasks/docker-container.yml
  vars:
    task_name: Fedora ssh container
    name:  ssh
    image: fedora-shell
    published_ports: "{{ ssh_container_port }}:{{ ssh_container_port }}"
    hostname: sh.segv.us
    volumes:
      - "{{ container_data_directory }}/ssh/home:/home:rw"
      - "{{ container_data_directory }}/ssh/host_keys:/etc/ssh/host_keys:rw"
    env:
      USER_NAME: "{{ primary_user_username }}"
      USER_SHELL: "{{ preferred_shell }}"
      USER_ID: "{{ primary_user_uid }}"
      TIMEZONE: "{{ timezone }}"

- include: user-preferences.yml
