- include_vars: secret_vars/user-account.yml

#- include: ../../../common_tasks/docker-image.yml
- include: common_tasks/docker-image.yml
  vars:
    task_name: CentOS ssh image
    name: jkoelndorfer/centos-shell
    tag: "{{ centos_ssh_version }}"

- include: common_tasks/docker-container.yml
  vars:
    task_name: CentOS ssh container
    name:  ssh
    image: "docker.io/jkoelndorfer/centos-shell:{{ centos_ssh_version }}"
    published_ports: "22:22"
    hostname: sh.segv.us
    env:
      SSH_AUTHORIZED_KEYS: "{{ primary_user_authorized_keys | join('\n') }}"
      SSH_SUDO: "ALL=(ALL) NOPASSWD: ALL"
      SSH_USER: "{{ primary_user_username }}"
      SSH_USER_PASSWORD: "{{ primary_user_password }}"
      SSH_USER_PASSWORD_HASHED: "true"
      SSH_USER_SHELL: "{{ preferred_shell }}"
      SSH_USER_ID: "{{ primary_user_uid }}"
