- name: include user account variables
  include_vars: secret_vars/user-account.yml

- include_role: name=docker-container private=True
  vars:
    container_name: ssh
    image_name: fedora-shell
    tag: latest
    git_repo: https://github.com/jkoelndorfer/docker-shell
    git_version: fedora
    published_ports:
      - "{{ ssh_container_port }}:22"
      - "60000:60000/udp"
      - "60001:60001/udp"
      - "60002:60002/udp"
      - "60003:60003/udp"
      - "60004:60004/udp"
      - "60005:60005/udp"
      - "60006:60006/udp"
      - "60007:60007/udp"
      - "60008:60008/udp"
      - "60009:60009/udp"
    hostname: sh.segv.us
    volumes:
      - src: home
        dest: /home
        owner: root
        group: root
        mode: "0755"
        mount_mode: rw

      - src: host_keys
        dest: /etc/ssh/host_keys
        mount_mode: rw
    env:
      USER_NAME: "{{ primary_user_username }}"
      USER_SHELL: "{{ preferred_shell }}"
      USER_ID: "{{ primary_user_uid }}"
      TIMEZONE: "{{ timezone }}"
  static: False

- name: configure user preferences
  include: user-preferences.yml
