- name: restart docker service (if exists)
  command: systemctl status docker
  become: True
  register: has_docker
  ignore_errors: true
  notify: restart docker service

- name: restart docker service
  service: name={{ docker_service }} state=restarted
  become: True
