---

- include_role: name=docker-container private=True
  vars:
    container_name: unifi
    image_name: docker.io/goofball222/unifi
    tag: release-5.4.14
    published_ports:
      - 3478:3478/udp
      - 6789:6789
      - 8080:8080
      - 8443:8443
      - 8880:8880
      - 8843:8843
      - 10001:10001/udp
    volumes:
      - src: data
        dest: /usr/lib/unifi/data
        owner: root
        group: root
        mode: "0700"
        mount_mode: rw

      - src: logs
        dest: /usr/lib/unifi/logs
        owner: root
        group: root
        mode: "0700"
        mount_mode: rw
  static: False
