---

- include_role: name=docker-container private=True
  vars:
    container_name: le-gen
    image_name: le-gen
    tag: latest
    state: started
    config_tasks: roles/le-gen/tasks/config.yml
    git_repo: https://github.com/jkoelndorfer/le-gen.git
    published_ports:
      - 80:80
    volumes:
      - src: certs
        dest: /certs
        mount_mode: rw
      - src: cert_renew.yml
        dest: /app/cert_renew.yml
        mount_mode: ro
        type: file
    env:
      REDIRECT_URL: "{{ redirect_url }}"
  static: False
