---

- name: include OS-specific docker variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: install Docker package
  become: True
  package: name={{ docker_package }} state=installed

- name: configure insecure Docker registry (local)
  include: insecure-docker-registry.yml
  delegate_to: localhost
  when: docker_insecure_registry

- name: configure insecure Docker registry
  include: insecure-docker-registry.yml
  when: docker_insecure_registry
