- name: restart sshd
  service: name={{ sshd_service_name }} state=restarted

- name: reload firewalld rules
  command: /usr/bin/firewall-cmd --reload
  notify: restart docker service

- name: restart docker service
  service: name=docker status=restarted
