---

# Not sure why this is necessary, but it is.
- name: update pacman cache
  shell: pacman -Sy --noconfirm
  become: True

- name: install needed system packages
  package: name={{ item }} state=installed
  become: True
  with_items:
    - base-devel
    - btrfs-progs
    - python

- name: install yay
  include: aur-pkg.yml pkg_name=yay
