- name: include OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install utility packages
  package: name={{ item }} state=installed
  with_items: "{{ utility_packages }}"

- include: user-account.yml
- include: firewall.yml
- include: ssh.yml

- name: Configure root authorized keys
  authorized_key: user=root key={{ item }}
  with_items: "{{ primary_user_authorized_keys }}"
  become: true
  become_user: root

- name: sudo nopasswd configuration
  template: src=sudo-nopasswd.j2 dest=/etc/sudoers.d/sudo-nopasswd owner=root group=root mode=0400
            validate='visudo -cf %s'

- include: local.yml

- name: primary data subvolume
  include: common_tasks/subvolume.yml
  vars:
    name: primary data
    path: /srv/data
    owner: root
    group: root
    mode: "0755"
