- include: user-account.yml
- include: firewall.yml
- include: ssh.yml

- name: Configure root authorized keys
  authorized_key: user=root key={{ item }}
  with_items: "{{ primary_user_authorized_keys }}"
  become: true
  become_user: root

- name: Disable SELinux
  selinux: state=disabled
  tags:
    - bootstrap

- template: src=sudo-nopasswd.j2 dest=/etc/sudoers.d/sudo-nopasswd owner=root group=root mode=0400
            validate='visudo -cf %s'
