- include: arch-base.yml
  when: ansible_os_family == "Archlinux"

- include: user-account.yml
- include: firewall.yml
- include: ssh.yml

- name: Install utility packages
  package: name={{ item }} state=installed
  with_items: "{{ utility_packages }}"

- name: Configure root authorized keys
  authorized_key: user=root key={{ item }}
  with_items: "{{ primary_user_authorized_keys }}"
  become: true
  become_user: root

- template: src=sudo-nopasswd.j2 dest=/etc/sudoers.d/sudo-nopasswd owner=root group=root mode=0400
            validate='visudo -cf %s'
