- include: user-account.yml
- include: firewall.yml
- include: ssh.yml

- name: Disable SELinux
  selinux: state=disabled
  tags:
    - bootstrap

- template: src=sudo-nopasswd.j2 dest=/etc/sudoers.d/sudo-nopasswd owner=root group=root mode=0400
            validate='visudo -cf %s'
