- name: sshd_config
  template: src=sshd_config.j2 dest={{ sshd_config_path }} owner=root group=root mode=0444
  notify:
    - restart sshd

- name: start and enable sshd
  service: name={{ sshd_service_name }} state=started enabled=yes
