---

- include_vars: "{{ ansible_os_family }}.yml"
- include_vars: secret_vars/user-account.yml

- name: Get primary user home
  shell: "getent passwd {{ primary_user_username }} | awk -F: '{ print $6 }'"
  register: primary_user_home

- name: Install git
  package: name={{ git_package }} state=installed

- include: common_tasks/configure-homedir.yml
  vars:
    - username: "{{ primary_user_username }}"
    - authorized_keys: "{{ primary_user_authorized_keys }}"
    - directory: "{{ primary_user_home.stdout }}"
