---

- include_vars: "{{ ansible_os_family }}.yml"
- include_vars: secret_vars/user-account.yml

- name: Get primary user home
  shell: "getent passwd {{ primary_user_username }} | awk -F: '{ print $6 }'"
  register: primary_user_home

- name: Install git
  package: name={{ git_package }} state=installed

- name: Checkout dotfiles repository
  git: repo={{ dotfiles_repository }} dest={{ primary_user_home.stdout }}/dotfiles
  become: yes
  become_user: "{{ primary_user_username }}"

- name: Set dotfiles permissions
  file: path={{ primary_user_home.stdout }}/dotfiles mode="u+rwX,go-w" owner={{ primary_user_username }}
  become: yes
  become_user: "{{ primary_user_username }}"

- name: Run dotfiles install script
  shell: "{{ preferred_shell }} -l -c 'SKIP_VIM_BUNDLE=y ./install'"
  args:
    chdir: "{{ primary_user_home.stdout }}/dotfiles"
  become: yes
  become_user: "{{ primary_user_username }}"
