---

- name: include router private variables
  include_vars: secret_vars/router.yml
  tags:
    - always

- name: apply UCI configuration -- WAN MAC address
  raw: uci set {{ item }}={{ router_wan_mac_address }}
  with_items:
    - network.wan.macaddr
    - network.wan6.macaddr
  tags:
    - config

- name: create nat64 interface
  raw: uci set "network.nat64=interface"
  tags:
    - config

- name: add nat64 interface to lan zone
  raw: uci delete   firewall.@zone[0].network; \
       uci add_list firewall.@zone[0].network=lan; \
       uci add_list firewall.@zone[0].network=nat64
  tags:
    - config

- name: apply UCI configuration
  raw: uci set '{{ item.key }}={{ item.value }}'
  with_dict: "{{ uci_config | combine(uci_config_secrets) }}"
  tags:
    - config

- name: apply firewall rules
  include: firewall.yml
  tags:
    - config
    - firewall

- name: configure dnsmasq
  include: dnsmasq.yml
  tags:
    - config
    - dnsmasq

- name: configure unbound
  include: unbound.yml
  tags:
    - config
    - unbound

- name: commit UCI configuration
  raw: uci commit
  tags:
    - config
    - firewall

- name: restart network
  raw: /etc/init.d/network restart
  tags:
    - config

- name: restart firewall
  raw: /etc/init.d/firewall restart
  tags:
    - config
    - firewall

- name: restart wifi
  raw: wifi
  tags:
    - config

- name: restart dnsmasq
  raw: /etc/init.d/dnsmasq restart
  tags:
    - config
    - dnsmasq

# /etc/init.d/unbound enable returns a non-zero exit code for some reason
#
# cover it up with "|| true"
- name: enable unbound
  raw: /etc/init.d/unbound enable || true
  tags:
    - config
    - unbound

- name: restart unbound
  raw: /etc/init.d/unbound restart
  tags:
    - config
    - unbound

- name: up nat64 interface
  raw: ifup nat64
  tags:
    - config
