---

- include: bootstrap.yml

- name: get temporary path for image download
  connection: local
  shell: mktemp --tmpdir router-image.XXXXXX
  register: router_image_mktemp
  when: router_image_url is defined

- name: set router_image_path
  connection: local
  set_fact:
    router_image_path: "{{ router_image_mktemp.stdout }}"
  when: router_image_url is defined

- name: download image
  connection: local
  get_url:
    url: "{{ router_image_url }}"
    dest: "{{ router_image_path }}"
    mode: 0444
    force: yes
  when: router_image_url is defined

- name: copy image file to router
  copy: src={{ router_image_path }} dest=/tmp/sysimage force=yes \
        owner=root group=root mode=0644 backup=no unsafe_writes=yes

- name: run sysupgrade
  raw: sysupgrade -n /tmp/sysimage
  ignore_errors: True

- name: remove old ssh host key
  connection: local
  shell: ssh-keygen -R {{ ansible_host }}
