---

- name: deploy Internet gateway service file
  template:
    src: internet-gateway.service.j2
    dest: "{{ systemd_service_directory }}/internet-gateway.service"
    owner: root
    group: root
    mode: 0444
  become: True
  notify:
    - reload systemd unit files
    - restart Internet gateway service

- name: deploy port forwarding service file
  template:
    src: portfw.service.j2
    dest: "{{ systemd_service_directory }}/portfw.service"
    owner: root
    group: root
    mode: 0444
  become: True
  notify:
    - reload systemd unit files
    - restart port forwarding service

- name: deploy port forwarding rules file
  template:
    src: portfw.rules.j2
    dest: "{{ portfw_rules_file }}"
    owner: root
    group: root
    mode: 0555
  become: True
  notify:
    - reload systemd unit files
    - restart port forwarding service

- name: create dhcpcd WAN override directory
  file:
    path: "{{ systemd_service_directory }}/dhcpcd@{{ router_wan_interface.name }}.service.d"
    state: directory
    owner: root
    group: root
    mode: 0555
  become: True

- name: deploy dhcpcd WAN interface service
  template:
    src: dhcpcd@wan.service.j2
    dest: "{{ systemd_service_directory }}/dhcpcd@{{ router_wan_interface.name }}.service.d/override.conf"
    owner: root
    group: root
    mode: 0444
  become: True
  notify: reload systemd unit files
  register: dhcpcd_wan_service

- name: run handlers
  meta: flush_handlers

- name: start Internet gateway service
  service: name=internet-gateway state=started enabled=True
  become: True

- name: start port forwarding service
  service: name=portfw state=started enabled=True
  become: True

- name: start dhcpcd WAN service
  service: name=dhcpcd@wan state=started enabled=True
  become: True
