---

# FIXME: This playbook won't run to completion on a freshly-provisioned server.
#
# The issue is that systemd-networkd can't simply be restarted in order to change
# network interface names. You have to actually reboot the system.

- name: configure network interfaces for routing
  include: interfaces.yml

- name: configure DNS service
  include: dns.yml
