---

- include_role: name=docker-container private=True
  vars:
    container_name: mumble
    image_name: docker.io/luzifer/mumble
    tag: latest
    # This mumble container doesn't expose 64738/tcp like it should,
    # so we need to do it ourselves.
    expose:
      - 64738
      - "64738/udp"
    published_ports:
      - "64738:64738"
      - "64738:64738/udp"
    volumes:
      - src: config
        dest: /config
        mount_mode: rw

      - src: "{{ container_data_directory }}/certs/fullchain.pem"
        dest: /config/ssl.crt
        mount_mode: ro
        type: file

      - src: "{{ container_data_directory }}/certs/key.pem"
        dest: /config/ssl.key
        mount_mode: ro
        type: file

      - src: data
        dest: /data
        mount_mode: rw
  static: False
