- include: common_tasks/docker-image.yml
  vars:
    task_name: Mumble container image
    name: luzifer/mumble
    tag: latest

- include: config.yml
  when: (state == "present") or (state == "started")

- include: common_tasks/docker-container.yml
  vars:
    task_name: Mumble container
    name:  mumble
    image: docker.io/luzifer/mumble:latest
    # This mumble container doesn't expose 64738/tcp like it should,
    # so we need to do it ourselves.
    expose:
      - 64738
      - "64738/udp"
    published_ports:
      - "64738:64738"
      - "64738:64738/udp"
    volumes:
      - "{{ container_config_directory }}/mumble:/config:ro"
      - "{{ container_data_directory }}/mumble:/data:rw"
