- name: "{{ task_name }} ({{ {'started': 'present', 'stopped': 'present'}.get(state, state) }})"
  docker_image:
    name: "{{ name }}"
    tag: "{{ tag }}"
    path: "{{ path | default(None) }}"
    force: "{{ container_image_force | default(false) }}"
    nocache: "{{ container_nocache | default(false) }}}"
    state: "{{ {'started': 'present', 'stopped': 'present'}.get(state, state) }}"
