sudo_group: wheel
git_package: git
zsh_package: zsh

ssh_sftp_subsystem: /usr/lib/ssh/sftp-server

utility_packages:
  - bind-tools
  - dmidecode
  - git
  - htop
  - neovim
  - net-tools
  - nmap
  - python
  - python2
  - python2-neovim
  - python-neovim
  - ruby
  - sudo
  - sysdig
  - tcpdump
  - tmux
