---

- include_role: name=docker-container private=True
  vars:
    container_name: crashplan
    image_name: docker-crashplan
    tag: latest
    git_repo: https://github.com/jkoelndorfer/docker-crashplan.git
    volumes:
      - src: /srv/data/hd0000
        dest: /srv/data/hd0000
        mount_mode: rw
      - src: /srv/data/container
        dest: /srv/data/container
        mount_mode: rw
      - src: crashplan
        dest: /var/crashplan
        mount_mode: rw
  static: False
