- name: check for owncloud data subvolume
  command: btrfs subvolume show {{ container_data_directory }}/owncloud
  register: owncloud_subvolume_result
  ignore_errors: True
  with_items: "{{ ansible_mounts }}"
  when:
    - item.mount == '/'
    - item.fstype == 'btrfs'

- name: create container owncloud data subvolume
  command: btrfs subvolume create {{ container_data_directory }}/owncloud
  when: owncloud_subvolume_result | failed

- file: path={{ container_data_directory }}/owncloud state=directory owner=root group=root mode=0700
- file: path={{ container_data_directory }}/owncloud/app state=directory \
        owner={{ owncloud_app_owner }} group=root mode=0700
- file: path={{ container_data_directory }}/owncloud/db state=directory \
        owner={{ owncloud_pg_owner }} group=root mode=0700
