- include_vars: secret_vars/owncloud.yml

- include: common_tasks/docker-image.yml
  vars:
    task_name: Owncloud Postgres image
    name: docker.io/postgres
    tag: "{{ owncloud_pg_version }}"

- include: common_tasks/docker-container.yml
  vars:
    task_name: Owncloud Postgres container
    name:  owncloud-db
    image: "postgres:{{ owncloud_pg_version }}"
    env:
      POSTGRES_USER:     "{{ owncloud_pg_username }}"
      POSTGRES_PASSWORD: "{{ owncloud_pg_password }}"

- include: common_tasks/docker-image.yml
  vars:
    task_name: Owncloud application image
    name: docker.io/owncloud
    tag: "{{ owncloud_version }}"

- include: common_tasks/docker-container.yml
  vars:
    task_name: Owncloud application container
    name:  owncloud-app
    image: "owncloud:{{ owncloud_version }}"
    links:
      - owncloud-db:db

- include: common_tasks/docker-image.yml
  vars:
    task_name: Owncloud SSL proxy image
    name: danieldent/nginx-ssl-proxy
    # "latest" is the only available tag
    tag:  latest
