- include_vars: secret_vars/owncloud.yml

- include: data.yml

- include: roles/docker-server/tasks/image.yml
  vars:
    task_name: Owncloud Postgres image
    name: docker.io/postgres
    tag: "{{ owncloud_pg_version }}"

- include: roles/docker-server/tasks/container.yml
  vars:
    task_name: Owncloud Postgres container
    name:  owncloud-db
    image: "postgres:{{ owncloud_pg_version }}"
    volumes:
      - "{{ container_data_directory }}/owncloud/db:/var/lib/postgresql/data"
    env:
      POSTGRES_USER:     "{{ owncloud_pg_username }}"
      POSTGRES_PASSWORD: "{{ owncloud_pg_password }}"

- include: app.yml

- include: roles/docker-server/tasks/image-from-git.yml
  vars:
    task_name: Owncloud SSL proxy image
    name: nginx-ssl-proxy
    tag:  latest
    git_repo: https://github.com/jkoelndorfer/nginx-ssl-proxy

- name: ssl proxy configuration directory
  file: path={{ container_config_directory }}/ssl-proxy state=directory mode=0755

- name: ssl proxy Diffie-Hellman parameters
  command: openssl dhparam -out {{ container_config_directory }}/ssl-proxy/dhparam 2048 \
           creates={{ container_config_directory }}/ssl-proxy/dhparam

- include: roles/docker-server/tasks/container.yml
  vars:
    task_name: nginx SSL proxy container
    name: nginx-ssl-proxy
    image: nginx-ssl-proxy
    published_ports: "443:443"
    links:
      - owncloud-app:owncloud
    volumes:
      - "{{ container_data_directory }}/certs/owncloud/fullchain.pem:/etc/secrets/proxycert"
      - "{{ container_data_directory }}/certs/owncloud/key.pem:/etc/secrets/proxykey"
      - "{{ container_config_directory }}/ssl-proxy/dhparam:/etc/secrets/dhparam"
    env:
      ENABLE_SSL: true
      TARGET_SERVICE: owncloud
