- name: include owncloud secrets
  include_vars: secret_vars/owncloud.yml

- include_role: name=docker-container private=True
  vars:
    container_name: owncloud-db
    image_name: docker.io/postgres
    tag: "{{ owncloud_pg_version }}"
    volumes:
      - src: postgres
        dest: /var/lib/postgresql/data
        mount_mode: rw
    env:
      POSTGRES_USER:     "{{ owncloud_pg_username }}"
      POSTGRES_PASSWORD: "{{ owncloud_pg_password }}"
  static: False

- include_role: name=docker-container private=True
  vars:
    container_name: owncloud-app
    image_name: docker.io/owncloud
    tag: "{{ owncloud_version }}"
    links:
      - owncloud-db:db
    volumes:
      - src: config
        dest: /var/www/html/config
        mount_mode: rw

      - src: data
        dest: /var/www/html/data
        mount_mode: rw
  static: False

- include_role: name=docker-container private=True
  vars:
    container_name: nginx-ssl-proxy
    image_name: nginx-ssl-proxy
    git_repo: https://github.com/jkoelndorfer/nginx-ssl-proxy
    config_tasks: roles/owncloud/tasks/ssl-proxy-config.yml
    published_ports: "443:443"
    tag: latest
    links:
      - owncloud-app:owncloud
    volumes:
      - src: dhparam
        dest: /etc/secrets/dhparam
        mount_mode: ro
        type: file

      - src: "{{ container_data_directory }}/certs/owncloud/fullchain.pem"
        dest: /etc/secrets/proxycert
        mount_mode: ro
        type: file

      - src: "{{ container_data_directory }}/certs/owncloud/key.pem"
        dest: /etc/secrets/proxykey
        mount_mode: ro
        type: file
    env:
      ENABLE_SSL: true
      TARGET_SERVICE: owncloud
  static: False
